export const exercises = [
  {
    id: "1",
    name: "Push-Up",
    muscleGroups: ["Chest", "Shoulders", "Triceps"],
    imageUrl: "/images/push-up.jpg",
    instructions: [
      "Start in a plank position with your hands directly under your shoulders.",
      "Lower your body until your chest nearly touches the floor.",
      "Keep your elbows at a 45-degree angle from your body.",
      "Push back up to the starting position.",
    ],
  },
  {
    id: "2",
    name: "Squat",
    muscleGroups: ["Quadriceps", "Hamstrings", "Glutes"],
    imageUrl: "/images/squat.jpg",
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Lower your body as if you're sitting back into a chair.",
      "Keep your chest up and your knees over your toes.",
      "Return to the starting position.",
    ],
  },
  {
    id: "3",
    name: "Plank",
    muscleGroups: ["Abdominals", "Lower Back", "Core"],
    imageUrl: "/images/plank.png",
    instructions: [
      "Start in a push-up position but bend your elbows and rest your weight on your forearms.",
      "Keep your body in a straight line from head to heels.",
      "Hold the position for the desired amount of time.",
      "Keep your abs tight and don't let your hips sag.",
    ],
  },
  {
    id: "4",
    name: "Bicep Curl",
    muscleGroups: ["Biceps"],
    imageUrl: "/images/biceps-curl.jpg",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Keep your elbows close to your torso and curl the weights up to shoulder level.",
      "Squeeze your biceps at the top of the movement.",
      "Slowly lower the weights back to the starting position.",
    ],
  },
  {
    id: "5",
    name: "Lunge",
    muscleGroups: ["Quadriceps", "Hamstrings", "Glutes"],
    imageUrl: "/images/lunge.jpg",
    instructions: [
      "Stand with your feet together.",
      "Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle.",
      "Keep your front knee directly above your ankle.",
      "Push back to the starting position and repeat on the other leg.",
    ],
  },
  {
    id: "6",
    name: "Deadlift",
    muscleGroups: ["Back", "Glutes", "Hamstrings"],
    imageUrl: "/images/deadlift.jpg",
    instructions: [
      "Stand with your feet hip-width apart, holding a barbell in front of you.",
      "Bend at your hips and knees to lower the barbell to the floor.",
      "Keep your back straight and your chest up.",
      "Lift the barbell by extending your hips and knees to stand up.",
    ],
  },
  {
    id: "7",
    name: "Bench Press",
    muscleGroups: ["Chest", "Shoulders", "Triceps"],
    imageUrl: "/images/bench-press.jpg",
    instructions: [
      "Lie on a flat bench with your feet flat on the floor.",
      "Grip the barbell with your hands slightly wider than shoulder-width apart.",
      "Lower the barbell to your chest.",
      "Push the barbell back up to the starting position.",
    ],
  },
  {
    id: "8",
    name: "Shoulder Press",
    muscleGroups: ["Shoulders", "Triceps"],
    imageUrl: "/images/shoulder-press.jpg",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Lift the dumbbells to shoulder height with your palms facing forward.",
      "Press the dumbbells overhead until your arms are fully extended.",
      "Lower the dumbbells back to shoulder height.",
    ],
  },
  {
    id: "9",
    name: "Tricep Dip",
    muscleGroups: ["Triceps"],
    imageUrl: "/images/triceps-dip.jpg",
    instructions: [
      "Place your hands on the edge of a bench or chair, fingers facing forward.",
      "Extend your legs out in front of you.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Push back up to the starting position.",
    ],
  },
  {
    id: "10",
    name: "Pull-Up",
    muscleGroups: ["Back", "Biceps"],
    imageUrl: "/images/pull-up.jpg",
    instructions: [
      "Grip a pull-up bar with your palms facing away from you.",
      "Hang with your arms fully extended.",
      "Pull your body up until your chin is above the bar.",
      "Lower your body back to the starting position.",
    ],
  },
  {
    id: "11",
    name: "Leg Press",
    muscleGroups: ["Quadriceps", "Hamstrings", "Glutes"],
    imageUrl: "/images/leg-press.jpg",
    instructions: [
      "Sit on a leg press machine with your feet shoulder-width apart on the platform.",
      "Lower the platform until your knees are at a 90-degree angle.",
      "Push the platform back up to the starting position.",
      "Keep your feet flat on the platform throughout the movement.",
    ],
  },
  {
    id: "12",
    name: "Russian Twist",
    muscleGroups: ["Obliques", "Core"],
    imageUrl: "/images/russian-twist.jpg",
    instructions: [
      "Sit on the floor with your knees bent and your feet flat.",
      "Lean back slightly and lift your feet off the floor.",
      "Hold a weight with both hands and twist your torso to the right.",
      "Twist back to the center, then to the left.",
    ],
  },
  {
    id: "13",
    name: "Calf Raise",
    muscleGroups: ["Calves"],
    imageUrl: "/images/calf-raise.jpg",
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Lift your heels off the ground as high as possible.",
      "Hold the position for a moment.",
      "Lower your heels back to the starting position.",
    ],
  },
  {
    id: "14",
    name: "Hammer Curl",
    muscleGroups: ["Biceps", "Forearms"],
    imageUrl: "/images/hammer-curl.jpg",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Keep your elbows close to your torso and curl the weights up to shoulder level.",
      "Squeeze your biceps at the top of the movement.",
      "Slowly lower the weights back to the starting position.",
    ],
  },
  {
    id: "15",
    name: "Glute Bridge",
    muscleGroups: ["Glutes", "Lower Back"],
    imageUrl: "/images/glute-bridge.png",
    instructions: [
      "Lie on your back with your knees bent and your feet flat on the floor.",
      "Lift your hips off the ground until your knees, hips, and shoulders form a straight line.",
      "Squeeze your glutes at the top of the movement.",
      "Lower your hips back to the starting position.",
    ],
  },
  {
    id: "16",
    name: "Mountain Climbers",
    muscleGroups: ["Core", "Legs", "Shoulders"],
    imageUrl: "/images/mountain-climber.jpg",
    instructions: [
      "Start in a plank position with your hands directly under your shoulders.",
      "Bring your right knee toward your chest.",
      "Quickly switch legs, bringing your left knee toward your chest.",
      "Continue alternating legs at a fast pace.",
    ],
  },
  {
    id: "17",
    name: "Burpee",
    muscleGroups: ["Full Body"],
    imageUrl: "/images/burpee.jpg",
    instructions: [
      "Start in a standing position.",
      "Drop into a squat position and place your hands on the ground.",
      "Kick your feet back into a plank position.",
      "Perform a push-up, then return your feet to the squat position.",
      "Jump up from the squat position.",
    ],
  },
  {
    id: "18",
    name: "Crunch",
    muscleGroups: ["Abdominals"],
    imageUrl: "/images/crunch.jpg",
    instructions: [
      "Lie on your back with your knees bent and feet flat on the floor.",
      "Place your hands behind your head.",
      "Lift your upper body towards your knees, exhaling as you go up.",
      "Inhale as you return to the starting position.",
    ],
  },
  {
    id: "19",
    name: "Reverse Fly",
    muscleGroups: ["Upper Back", "Shoulders"],
    imageUrl: "/images/reverse-fly.png",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Bend at your hips until your torso is nearly parallel to the floor.",
      "With a slight bend in your elbows, lift the weights out to the sides until your upper arms are in line with your body.",
      "Slowly lower the weights back to the starting position.",
    ],
  },
  {
    id: "20",
    name: "Side Plank",
    muscleGroups: ["Obliques", "Core"],
    imageUrl: "/images/side-plank.png",
    instructions: [
      "Lie on your side with your legs straight.",
      "Prop yourself up on your elbow and the side of your foot.",
      "Raise your hips until your body forms a straight line from head to feet.",
      "Hold the position for the desired amount of time.",
      "Repeat on the other side.",
    ],
  },
];
